/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "surface-container-lowest": "#0e0e0e",
              "tertiary-fixed-dim": "#ffb2bf",
              "primary-fixed": "#7ffc97",
              "on-surface-variant": "#bdcaba",
              "surface-dim": "#131313",
              "on-primary-fixed": "#002109",
              "secondary-container": "#404752",
              "surface-container-highest": "#353535",
              "error-container": "#93000a",
              "text-muted": "#9CA3AF",
              "on-secondary-fixed": "#151c25",
              "on-tertiary-fixed-variant": "#8a143c",
              "surface-pitch": "#0A0A0A",
              "on-error-container": "#ffdad6",
              "background": "#131313",
              "error": "#ffb4ab",
              "on-background": "#e2e2e2",
              "on-secondary-container": "#afb5c2",
              "tertiary": "#ffb2bf",
              "primary-fixed-dim": "#62df7d",
              "surface-container-low": "#1b1b1b",
              "inverse-primary": "#006e2d",
              "surface-elevated": "#171717",
              "on-tertiary-fixed": "#3f0016",
              "on-secondary": "#2a313b",
              "terminal-green": "#16A34A",
              "tertiary-container": "#ec6284",
              "on-primary-fixed-variant": "#005320",
              "border-subtle": "#262626",
              "surface-bright": "#393939",
              "on-error": "#690005",
              "on-secondary-fixed-variant": "#404752",
              "inverse-on-surface": "#303030",
              "secondary-fixed-dim": "#c0c7d3",
              "secondary": "#c0c7d3",
              "on-primary-container": "#003111",
              "outline": "#879485",
              "primary": "#62df7d",
              "surface-container": "#1f1f1f",
              "inverse-surface": "#e2e2e2",
              "surface-container-high": "#2a2a2a",
              "surface-tint": "#62df7d",
              "tertiary-fixed": "#ffd9de",
              "secondary-fixed": "#dce3f0",
              "on-primary": "#003914",
              "primary-container": "#1ca64d",
              "on-tertiary-container": "#5a0022",
              "on-tertiary": "#660027",
              "surface-variant": "#353535",
              "surface": "#131313",
              "outline-variant": "#3e4a3d",
              "on-surface": "#e2e2e2"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "spacing": {
              "container-max": "1200px",
              "base": "8px",
              "gutter": "24px",
              "section-gap": "120px",
              "margin-mobile": "16px"
      },
      "fontFamily": {
              "label-caps": ["JetBrains Mono"],
              "display-lg": ["Space Grotesk"],
              "body-base": ["Hanken Grotesk"],
              "headline-md": ["Space Grotesk"],
              "display-lg-mobile": ["Space Grotesk"],
              "code-sm": ["JetBrains Mono"]
      },
      "fontSize": {
              "label-caps": ["12px", {"lineHeight": "1.0", "letterSpacing": "0.1em", "fontWeight": "600"}],
              "display-lg": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700"}],
              "body-base": ["16px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
              "headline-md": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600"}],
              "display-lg-mobile": ["40px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700"}],
              "code-sm": ["14px", {"lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
